      MODULE RAYLIB
      TYPE VECTOR2
            REAL X
            REAL Y
      END TYPE VECTOR2
      TYPE VECTOR3
            REAL X
            REAL Y
            REAL Z
      END TYPE VECTOR3
      TYPE VECTOR4
            REAL X
            REAL Y
            REAL Z
            REAL W
      END TYPE VECTOR4
      TYPE MATRIX
            REAL M0
            REAL M4
            REAL M8
            REAL M12
            REAL M1
            REAL M5
            REAL M9
            REAL M13
            REAL M2
            REAL M6
            REAL M10
            REAL M14
            REAL M3
            REAL M7
            REAL M11
            REAL M15
      END TYPE MATRIX
      TYPE COLOR
            CHARACTER*1 R
            CHARACTER*1 G
            CHARACTER*1 B
            CHARACTER*1 A
      END TYPE COLOR
      TYPE RECTANGLE
            REAL X
            REAL Y
            REAL WIDTH
            REAL HEIGHT
      END TYPE RECTANGLE
      TYPE IMAGE
            INTEGER POINTER DATA
            INTEGER WIDTH
            INTEGER HEIGHT
            INTEGER MIPMAPS
            INTEGER FORMAT
      END TYPE IMAGE
      TYPE TEXTURE
            INTEGER ID
            INTEGER WIDTH
            INTEGER HEIGHT
            INTEGER MIPMAPS
            INTEGER FORMAT
      END TYPE TEXTURE
      TYPE RENDERTEXTURE
            INTEGER ID
            TYPE(TEXTURE) TEXTURE
            TYPE(TEXTURE) DEPTH
      END TYPE RENDERTEXTURE
      TYPE NPATCHINFO
            TYPE(RECTANGLE) SOURCE
            INTEGER LEFT
            INTEGER TOP
            INTEGER RIGHT
            INTEGER BOTTOM
            INTEGER LAYOUT
      END TYPE NPATCHINFO
      TYPE GLYPHINFO
            INTEGER VALUE
            INTEGER OFFSETX
            INTEGER OFFSETY
            INTEGER ADVANCEX
            TYPE(IMAGE) IMAGE
      END TYPE GLYPHINFO
      TYPE FONT
            INTEGER BASESIZE
            INTEGER GLYPHCOUNT
            INTEGER GLYPHPADDING
            TYPE(TEXTURE) TEXTURE
            TYPE(RECTANGLE) RECS
            TYPE(GLYPHINFO) GLYPHS
      END TYPE FONT
      TYPE CAMERA3D
            TYPE(VECTOR3) POSITION
            TYPE(VECTOR3) TARGET
            TYPE(VECTOR3) UP
            REAL FOVY
            INTEGER PROJECTION
      END TYPE CAMERA3D
      TYPE CAMERA2D
            TYPE(VECTOR2) OFFSET
            TYPE(VECTOR2) TARGET
            REAL ROTATION
            REAL ZOOM
      END TYPE CAMERA2D
      TYPE MESH
            INTEGER VERTEXCOUNT
            INTEGER TRIANGLECOUNT
            REAL VERTICES
            REAL TEXCOORDS
            REAL TEXCOORDS2
            REAL NORMALS
            REAL TANGENTS
            CHARACTER*1 COLORS
            INTEGER*2 INDICES
            REAL ANIMVERTICES
            REAL ANIMNORMALS
            CHARACTER*1 BONEIDS
            REAL BONEWEIGHTS
            INTEGER VAOID
            INTEGER VBOID
      END TYPE MESH
      TYPE SHADER
            INTEGER ID
            INTEGER LOCS
      END TYPE SHADER
      TYPE MATERIALMAP
            TYPE(TEXTURE) TEXTURE
            TYPE(COLOR) COLOR
            REAL VALUE
      END TYPE MATERIALMAP
      TYPE MATERIAL
            TYPE(SHADER) SHADER
            TYPE(MATERIALMAP) MAPS
            REAL PARAMS
      END TYPE MATERIAL
      TYPE TRANSFORM
            TYPE(VECTOR3) TRANSLATION
            TYPE(VECTOR4) ROTATION
            TYPE(VECTOR3) SCALE
      END TYPE TRANSFORM
      TYPE BONEINFO
            CHARACTER*1 NAME
            INTEGER PARENT
      END TYPE BONEINFO
      TYPE MODEL
            TYPE(MATRIX) TRANSFORM
            INTEGER MESHCOUNT
            INTEGER MATERIALCOUNT
            TYPE(MESH) MESHES
            TYPE(MATERIAL) MATERIALS
            INTEGER MESHMATERIAL
            INTEGER BONECOUNT
            TYPE(BONEINFO) BONES
            TYPE(TRANSFORM) BINDPOSE
      END TYPE MODEL
      TYPE MODELANIMATION
            INTEGER BONECOUNT
            INTEGER FRAMECOUNT
            TYPE(BONEINFO) BONES
            TYPE(TRANSFORM) FRAMEPOSES
            CHARACTER*1 NAME
      END TYPE MODELANIMATION
      TYPE RAY
            TYPE(VECTOR3) POSITION
            TYPE(VECTOR3) DIRECTION
      END TYPE RAY
      TYPE RAYCOLLISION
            BYTE HIT
            REAL DISTANCE
            TYPE(VECTOR3) POINT
            TYPE(VECTOR3) NORMAL
      END TYPE RAYCOLLISION
      TYPE BOUNDINGBOX
            TYPE(VECTOR3) MIN
            TYPE(VECTOR3) MAX
      END TYPE BOUNDINGBOX
      TYPE WAVE
            INTEGER FRAMECOUNT
            INTEGER SAMPLERATE
            INTEGER SAMPLESIZE
            INTEGER CHANNELS
            INTEGER POINTER DATA
      END TYPE WAVE
      TYPE RAUDIOBUFFER
      END TYPE RAUDIOBUFFER
      TYPE RAUDIOPROCESSOR
      END TYPE RAUDIOPROCESSOR
      TYPE AUDIOSTREAM
            TYPE(RAUDIOBUFFER) BUFFER
            TYPE(RAUDIOPROCESSOR) PROCESSOR
            INTEGER SAMPLERATE
            INTEGER SAMPLESIZE
            INTEGER CHANNELS
      END TYPE AUDIOSTREAM
      TYPE SOUND
            TYPE(AUDIOSTREAM) STREAM
            INTEGER FRAMECOUNT
      END TYPE SOUND
      TYPE MUSIC
            TYPE(AUDIOSTREAM) STREAM
            INTEGER FRAMECOUNT
            BYTE LOOPING
            INTEGER CTXTYPE
            INTEGER POINTER CTXDATA
      END TYPE MUSIC
      TYPE VRDEVICEINFO
            INTEGER HRESOLUTION
            INTEGER VRESOLUTION
            REAL HSCREENSIZE
            REAL VSCREENSIZE
            REAL EYETOSCREENDISTANCE
            REAL LENSSEPARATIONDISTANCE
            REAL INTERPUPILLARYDISTANCE
            REAL LENSDISTORTIONVALUES
            REAL CHROMAABCORRECTION
      END TYPE VRDEVICEINFO
      TYPE VRSTEREOCONFIG
            TYPE(MATRIX) PROJECTION
            TYPE(MATRIX) VIEWOFFSET
            REAL LEFTLENSCENTER
            REAL RIGHTLENSCENTER
            REAL LEFTSCREENCENTER
            REAL RIGHTSCREENCENTER
            REAL SCALE
            REAL SCALEIN
      END TYPE VRSTEREOCONFIG
      TYPE FILEPATHLIST
            INTEGER CAPACITY
            INTEGER COUNT
            CHARACTER*1 PATHS
      END TYPE FILEPATHLIST
      TYPE AUTOMATIONEVENT
            INTEGER FRAME
            INTEGER TYPE
            INTEGER PARAMS
      END TYPE AUTOMATIONEVENT
      TYPE AUTOMATIONEVENTLIST
            INTEGER CAPACITY
            INTEGER COUNT
            TYPE(AUTOMATIONEVENT) EVENTS
      END TYPE AUTOMATIONEVENTLIST
      TYPE RLVERTEXBUFFER
            INTEGER ELEMENTCOUNT
            REAL VERTICES
            REAL TEXCOORDS
            CHARACTER*1 COLORS
            INTEGER INDICES
            INTEGER VAOID
            INTEGER VBOID
      END TYPE RLVERTEXBUFFER
      TYPE RLDRAWCALL
            INTEGER MODE
            INTEGER VERTEXCOUNT
            INTEGER VERTEXALIGNMENT
            INTEGER TEXTUREID
      END TYPE RLDRAWCALL
      TYPE RLRENDERBATCH
            INTEGER BUFFERCOUNT
            INTEGER CURRENTBUFFER
            TYPE(RLVERTEXBUFFER) VERTEXBUFFER
            TYPE(RLDRAWCALL) DRAWS
            INTEGER DRAWCOUNTER
            REAL CURRENTDEPTH
      END TYPE RLRENDERBATCH

      TYPE FLOAT3
            REAL V
      END TYPE FLOAT3
      TYPE FLOAT16
            REAL V
      END TYPE FLOAT16


      END MODULE
